### ISSUE TITLE
Project organization

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharpMDXS#5]
I got a few GitHub notifications about this project. What is the relationship between this and https://github.com/fsharp/fsharpbinding? Is there a plan to move Xamarin studio/MonoDevelop code to this repo and remove it from fsharpbinding?

**Comment by 7sharp9** [comment]
Yes, exactly that.  This repo is currently used as a submodule of Monodevelop/Roslyn

**Comment by tpetricek** [comment]
Oh, I see. Should the "monodevelop" folder be deleted from the "fsharpbinding" project? (At the moment, it is still there...)

**Comment by 7sharp9** [comment]
Eventually yes, MD 5.9 still uses this as its submodule.
