### ISSUE TITLE
Comment toggling doesn't work in Xamarin Studio on OS X

### ISSUE THREAD

**Issue by paulyoung** [fsharp/FSharpMDXS#7]
In Xamarin Studio on OS X, `⌘ + /` should toggle comments for the current line or selection. This isn't working for me in Version 5.8.3 (build 1).

Apologies if this issue isn't related to this project.

**Comment by paulyoung** [comment]
If this is the right place I'd happily provide a pull request with a fix for this if someone could point me in the right direction.

**Comment by paulyoung** [comment]
This looks relevant: https://github.com/fsharp/FSharpMDXS/blob/df56d0249df9f7b5a8562b54c9abea2136e07e13/MonoDevelop.FSharpBinding/FSharpLanguageBinding.fs#L87-L90

**Comment by 7sharp9** [comment]
I believe this was fixed in the 5.9 release

**Comment by paulyoung** [comment]
Sounds like I should be checking out the Alpha/Beta channels.

**Comment by paulyoung** [comment]
I just got 5.9 (build 431) on the Stable channel and this works as expected.

Thanks @7sharp9!
