### ISSUE TITLE
Async is not highlighted as other types

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharpMDXS#8]

**Comment by 7sharp9** [comment]
![screen shot 2015-05-01 at 08 40 28](https://cloud.githubusercontent.com/assets/588746/7427909/c5ef424a-efdd-11e4-8ba6-c4864bb0cf62.png)

**Comment by rojepp** [comment]
I don't see the problem here?

**Comment by 7sharp9** [comment]
Async should be highlighted orange, if you add async extensions from Extcore for example it is highlighted in those.

**Comment by rojepp** [comment]
Oh, you're referring to `Async.StartAsTask`above?

**Comment by 7sharp9** [comment]
Yep, in this for some reason the symbol for Async is not a class
